title: AwardsNom
description: An award show ballot for Oscars, Emmys and Tonys
keywords: filmmaking, oscards, awards, goldenglobes
baseurl: "" 
url: "https://awardsnom.com"
twitter: awardsnom
github: melvitax/awardsnom
socialimage: http://awardsnom.com/assets/socialimage.jpg
socialinfo: "An award show nominee ballot tracker"
author:
  name: Melvin Rivera
  twitter: melvitax
  role: designer/developer
markdown: kramdown
exclude: ["node_modules",  "package.json", "Gemfile", "Gemfile.lock", "README.md", "LICENSE"]
timezone: 'America/New_York'
cloudKitApiToken: "453f7abfc9c751c71eaf871d9d88eefc2b0def21f19f77a3e517238ff0c889b5"
cloudKitEnvironment: "production"
fonts:
  - "Lato:400,900,700,500,300,100:latin"
sass:
    style: compressed
    sass_dir: styles
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]