title: AwardsNom
description: Nominee ballot tracker for award shows
keywords: filmmaking, oscards, awards, goldenglobes
baseurl: "" 
url: "https://awardsnom.com"
twitter: awardsnom
github: melvitax/awardsnom
socialimage: http://awardsnom.com/assets/images/social-sharing.jpg
socialinfo: "Nominee ballot tracker for award shows"
author:
  name: Melvin Rivera
  twitter: melvitax
  role: designer/developer
markdown: kramdown
exclude: ["node_modules",  "package.json", "Gemfile", "Gemfile.lock", "README.md", "LICENSE"]
timezone: 'America/New_York'
cloudKitApiToken: "94d9b5bf1c7d0d906288b87ea68985c7110a903bb78946c9517157b8b74ad14b"
cloudKitEnvironment: "production"
fonts:
  - "Lato:400,900,700,500,300,100:latin"
sass:
    style: compressed
    sass_dir: assets/css
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]