# config.yml

backend:
  name: git-gateway
  branch: main
  repo: melvitax/awardsnom.com 
media_folder: 'assets/uploads'
collections:
  - label: "Categories"
    name: "categories"
    folder: "_data/categories"
    format: yml
    create: true
    identifier_field: title
    fields:
      - {label: "Name", name: "title", widget: string}
  - label: "Oscars 2021"
    folder: "_oscars/2021"
    name: "oscars-2021"
    label_singular: Nominee
    format: frontmatter
    create: true
    media_folder: 'images'
    public_folder: ''
    fields: 
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Trailer, name: trailer, widget: string, required: false}
      - label: Nominations
        label_singular: Nomination
        name: nominations
        required: true
        widget: list
        fields:
          - label: Category
            name: category
            required: true
            widget: relation
            collection: categories
            searchFields: ["title"]
            displayFields: ["title"]
            valueField: "title"
          - {label: Name, name: name, widget: string, required: false}
          - {label: Subtitle, name: sub, widget: string, required: false}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Winner, name: winner, widget: boolean, default: false}