# config.yml

backend:
  name: git-gateway
  branch: main
  repo: melvitax/awardsnom.com 
media_folder: 'assets/uploads'
collections:
  - label: "Categories"
    name: "emmys-categories"
    create: true
    files:
      - label: "Categories"
        name: "categories"
        file: "_data/categories.yml"
        fields:
          - label: Oscars Categories
            label_singular: Category
            name: oscars-category
            required: true
            widget: list
            identifier_field: title
            fields:
            - {label: "Name", name: "title", widget: string}
          - label: Emmys Categories
            label_singular: Category
            name: emmys-category
            required: true
            widget: list
            identifier_field: title
            fields:
            - {label: "Name", name: "title", widget: string}
  - label: "Oscars"
    label_singular: Oscar Show
    name: "oscar-show"
    folder: "_oscars"
    format: frontmatter
    create: true
    identifier_field: title
    media_folder: ''
    public_folder: ''
    nested:
      depth: 2
      summary: '{{title}}'
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields: 
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Trailer, name: trailer, widget: string, required: false}
      - label: Nominations
        label_singular: Nomination
        name: nominations
        required: true
        widget: list
        fields:
          - label: Category
            name: category
            required: true
            widget: relation
            collection: oscars-category
            searchFields: ["title"]
            displayFields: ["title"]
            valueField: "title"
          - {label: Name, name: name, widget: string, required: false}
          - {label: Subtitle, name: sub, widget: string, required: false}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Winner, name: winner, widget: boolean, default: false}