# config.yml

backend:
  name: git-gateway
  branch: main
  repo: melvitax/awardsnom.com 
media_folder: 'assets/uploads'
collections:
  - label: "Categories"
    name: "categories"
    folder: "_data/categories"
    format: yml
    create: true
    identifier_field: title
    fields:
      - {label: "Name", name: "title", widget: string}
  - label: "Oscars"
    folder: "oscars"
    name: "oscars"
    label_singular: Year
    format: frontmatter
    create: true
    media_folder: 'images'
    public_folder: ''
    fields:
      - label: "Year"
        date: "year"
        widget: "datetime"
        default: "2021"
        date_format: "YYYY"
        time_format: false
        format: "YYYY"
        picker_utc: false
      - name: "{{date | date('YYYY')}}"
      - label: Nominees
        label_singular: Nominee
        name: nominees
        required: true
        widget: list
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Trailer, name: trailer, widget: string, required: false}
          - label: Nominations
            label_singular: Nomination
            name: nominations
            required: true
            widget: list
            fields:
              - label: Category
                name: category
                required: true
                widget: relation
                collection: categories
                searchFields: ["title"]
                displayFields: ["title"]
                valueField: "title"
              - {label: Name, name: name, widget: string, required: false}
              - {label: Sub, name: sub, widget: string, required: false}
              - {label: Image, name: image, widget: image, required: false}
              - {label: Winner, name: winner, widget: boolean, default: false}